Jb initial commit
Senzing/g2explorer pull request #15
Opened 2021-08-20 05:37 UTC by jbutcher21

initial commit and documentation

2021-08-20 13:09 UTC, antaenc commented on README.md
> +The [G2Explorer.py](G2Explorer.py) utility is an interactive command line utility that allows a user to ...
Remove 3 dots, colon instead

2021-08-20 13:09 UTC, antaenc commented on README.md
> +- **search** - Find an entity by name, DOB, address, etc.
Spell out date of birth

2021-08-20 13:10 UTC, antaenc commented on README.md
> +- **export** – Export the json records that make up an entity for debugging or reingesting after tweaks are made.
configuration changes instead of tweaks

2021-08-20 13:10 UTC, antaenc commented on README.md
> +It can also be used to view the reports generated by the following companion projects ...
3 dots, use colon

2021-08-20 13:11 UTC, antaenc commented on README.md
> +- python 3.6 or higher
Uppercase Python

2021-08-20 13:11 UTC, antaenc commented on README.md
> +1. Simply place the the following files in a directory of your choice ...
Double the

2021-08-20 13:13 UTC, antaenc commented on README.md
> +The best documentation for how to use the G2Explorer and its companion projects is located here ...
Further documentation for using G2Explorer and it's companion utilities can be located at:

2021-08-20 13:13 UTC, antaenc commented on README.md
> +But here are some basics ..
Getting started with some basic uses:

2021-08-20 13:14 UTC, antaenc commented on README.md
> +Next thing to do is to just start exploring your database!  Here are a few tips ...
The next thing to do is start exploring

3 dots

2021-08-20 13:15 UTC, antaenc requested changes
Some small cleanup

2021-08-20 17:11 UTC, jbutcher21 commented
Changes made, Ant, please review and approve.

2021-08-23 14:22 UTC, antaenc approved these changes

2021-08-23 14:23 UTC, antaenc commented
Changes approved

2021-08-23 14:23 UTC, merged